name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]  # Cross-browser testing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to use Node.js 16 support

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pytest pytest-playwright allure-pytest
          playwright install  # This ensures all browsers (Chromium, Firefox, Webkit) are installed

      - name: Run Tests
        run: pytest --browser=${{ matrix.browser }} --alluredir=reports/allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: allure-report
          path: reports/allure-results
