#
#name: CI Integration with Allure Reporting
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        browser: [chromium, firefox, webkit]
#
#    steps:
#      # Step 1: Checkout the repository
#      - name: Checkout Code
#        uses: actions/checkout@v4
#
#      # Step 2: Set up Node.js (to avoid deprecation issues)
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#
#      # Step 3: Set up Python
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.12.2'
#
#      # Step 4: Install dependencies including Allure
#      - name: Install Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pytest pytest-playwright allure-pytest pytest-rerunfailures pytest-timeout
#          playwright install --with-deps
#
#      # Step 5: Install Allure CLI manually (using direct download)
#      - name: Install Allure CLI
#        run: |
#          curl -o allure-2.20.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.20.0/allure-2.20.0.tgz
#          tar -zxvf allure-2.20.0.tgz
#          sudo mv allure-2.20.0 /opt/allure
#          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
#          allure --version
#
#      # Step 6: Ensure Allure Results Directory exists
#      - name: Ensure Allure Results Directory
#        run: mkdir -p reports/allure-results
#
#      # Step 7: Ensure Logs Directory exists
#      - name: Ensure Logs Directory
#        run: mkdir -p logs
#
#      # Step 8: Run the tests and generate Allure results
#      - name: Run Tests
#        run: |
#          pytest --alluredir=reports/allure-results --browser=${{ matrix.browser }} --reruns 2 --timeout=180000 -vv | tee logs/pytest_output.log
#        env:
#          PYTHONUNBUFFERED: 1
#
#      # Step 9: Debug Allure Results Directory
#      - name: List Allure Results Directory
#        run: ls -l reports/allure-results
#
#      # Step 10: Capture Logs on Failure
#      - name: Capture Logs on Failure
#        if: failure()
#        run: |
#          echo "Capturing logs after failure..."
#          cat logs/pytest_output.log || echo "No pytest output found."
#          cat reports/allure-results || echo "No Allure results found."
#
#      # Step 11: Verify Allure Results Directory
#      - name: Verify Allure Results Directory
#        run: |
#          if [ ! -d "reports/allure-results" ]; then
#            echo "Allure results directory not found!"
#            exit 1
#          else
#            echo "Allure results directory exists."
#          fi
#
#      # Step 12: Generate the Allure report
#      - name: Generate Allure Report
#        run: |
#          allure generate reports/allure-results --clean || echo "Allure report generation failed"
#
#      # Step 13: Upload Allure report as an artifact
#      - name: Upload Allure Report
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-report-${{ matrix.browser }}-${{ github.run_id }}
#          path: allure-report
#
#      # Step 14: Upload Playwright Screenshots for Debugging
#      - name: Upload Playwright Screenshots
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v4
#        with:
#          name: playwright-screenshots-${{ matrix.browser }}-${{ github.run_id }}
#          path: failure_*.png
#
#      # Step 15: Upload Pytest Logs for Debugging
#      - name: Upload Pytest Logs
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v4
#        with:
#          name: pytest-logs-${{ matrix.browser }}-${{ github.run_id }}
#          path: logs/pytest_output.log





name: CI Integration with Allure Reporting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (to avoid deprecation issues)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      # Step 4: Install dependencies including Allure
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright allure-pytest pytest-rerunfailures pytest-timeout
          playwright install --with-deps

      # Step 5: Install Allure CLI manually (using direct download)
      - name: Install Allure CLI
        run: |
          curl -o allure-2.20.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.20.0/allure-2.20.0.tgz
          tar -zxvf allure-2.20.0.tgz
          sudo mv allure-2.20.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version

      # Step 6: Ensure Allure Results Directory exists
      - name: Ensure Allure Results Directory
        run: mkdir -p reports/allure-results

      # Step 7: Ensure Logs Directory exists
      - name: Ensure Logs Directory
        run: mkdir -p logs

      # Step 8: Run the tests and generate Allure results
      - name: Run Tests
        run: |
          pytest --alluredir=reports/allure-results --browser=${{ matrix.browser }} --reruns 2 --timeout=180000 -vv | tee logs/pytest_output.log
        env:
          PYTHONUNBUFFERED: 1
          CI: true  # Add CI environment variable

      # Step 9: Debug Allure Results Directory
      - name: List Allure Results Directory
        run: ls -l reports/allure-results

      # Step 10: Capture Logs on Failure
      - name: Capture Logs on Failure
        if: failure()
        run: |
          echo "Capturing logs after failure..."
          cat logs/pytest_output.log || echo "No pytest output found."
          cat reports/allure-results || echo "No Allure results found."

      # Step 11: Verify Allure Results Directory
      - name: Verify Allure Results Directory
        run: |
          if [ ! -d "reports/allure-results" ]; then
            echo "Allure results directory not found!"
            exit 1
          else
            echo "Allure results directory exists."
          fi

      # Step 12: Generate the Allure report
      - name: Generate Allure Report
        run: |
          allure generate reports/allure-results --clean || echo "Allure report generation failed"

      # Step 13: Upload Allure report as an artifact
      - name: Upload Allure Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}-${{ github.run_id }}
          path: allure-report

      # Step 14: Upload Playwright Screenshots for Debugging
      - name: Upload Playwright Screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots-${{ matrix.browser }}-${{ github.run_id }}
          path: failure_*.png

      # Step 15: Upload Pytest Logs for Debugging
      - name: Upload Pytest Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs-${{ matrix.browser }}-${{ github.run_id }}
          path: logs/pytest_output.log


